name: Modules
on:
  pull_request:
    branches: [ master ]
jobs:
  test-posh:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests (PowerShell)
      run: |
        Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
        Set-PSRepository psgallery -InstallationPolicy trusted
        Install-Module ExchangeOnlineManagement, AzureADPreview      
      shell: powershell
