name: Publish PowerShell Module

on:
  release:
    types: [published]

jobs:
  publish-to-gallery:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish
      env:
        NUGET_KEY: $
      shell: pwsh
      run: |
        .\build\build.ps1
        Publish-Module -Path .\soa -NuGetApiKey $env:NUGET_KEY -Verbose