name: Publish PowerShell Module

on:
  release:
    types: [published]

jobs:
  publish-to-gallery:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - name: Build module
      env:
        MODULE_VER: ${{ github.ref_name }}
      shell: pwsh
      run: |
        .\.github\build\build.ps1
        Update-ModuleManifest -Path ".\SOA\SOA.psd1" -ModuleVersion ($env:MODULE_VER).TrimStart("v")
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add --all .
        git commit -am "Bump version"
        git push
        git push origin :refs/tags/$env:MODULE_VER
        git tag -fa $env:MODULE_VER
        git push origin --tags
    - name: Publish to PSGallery
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
      shell: pwsh
      run: |
        #Publish-Module -Path ".\SOA" -NuGetApiKey $env:NUGET_KEY -Verbose -WhatIf